baseURL = "https://chipper26.github.io/efektifpedia/"
languageCode = "id-id"
title = "efektifpedia"

[pagination]
pagerSize = 5

[params]
description = "Jasa penulisan artikel profesional"

[permalinks]
blog = "/blog/:slug/"