backend:
  name: github
  repo: chipper26/efektifpedia
  branch: main
  base_url: https://api.sveltia.org
  auth_endpoint: /auth

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  # Folder 1: Untuk artikel yang sudah tayang di website
  - name: "blog"
    label: "Artikel Publish"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} (Tayang)"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Penulis", name: "author", widget: "select", options: ["TRI IRAWAN", "Budi Darmawan"], default: "TRI IRAWAN" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Edukasi", "Tips", "Tech News","Digital Insight","Review & Tutorial","Life at Tech","Innovation"], default: "Edukasi" }
      - { label: "Tanggal", name: "date", widget: "datetime" }

  # Folder 2: Khusus untuk simpan Draft (disimpan di folder berbeda agar tidak terbaca script web)
  - name: "drafts"
    label: "Artikel Draft"
    folder: "drafts" # Folder baru di GitHub untuk draf
    create: true
    slug: "draft-{{slug}}"
    summary: "{{title}} (Belum Publish)"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Penulis", name: "author", widget: "select", options: ["TRI IRAWAN", "Budi Darmawan"], default: "TRI IRAWAN" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Edukasi", "Tips", "Berita"], default: "Edukasi" }
      - { label: "Tanggal", name: "date", widget: "datetime" }