backend:
  name: github
  repo: chipper26/efektifpedia
  branch: main
  base_url: https://api.sveltia.org
  auth_endpoint: /auth

site_url: https://chipper26.github.io/efektifpedia/
display_url: https://chipper26.github.io/efektifpedia/

# Lokasi penyimpanan file gambar
media_folder: "img/uploads"
# Alamat yang akan tertulis di file Markdown (Wajib pakai '/' di depan)
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      
      # Tambahkan Field Thumbnail di sini agar bisa upload gambar
      - { label: "Gambar Utama (Thumbnail)", name: "thumbnail", widget: "image", required: false }
      
      - label: "Penulis"
        name: "author"
        widget: "select"
        options:
          - "TRI IRAWAN"
          - "Budi Darmawan"
        default: "TRI IRAWAN"

      - label: "Kategori"
        name: "category"
        widget: "select"
        options: ["Edukasi", "Tips", "Berita", "Opini"]
        default: "Edukasi"
        
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }