backend:
  name: github
  repo: chipper26/efektifpedia
  branch: main
  # Gunakan gateway Sveltia yang sudah kamu daftarkan di callback URL tadi
  base_url: https://api.sveltia.org
  auth_endpoint: /auth

site_url: https://chipper26.github.io/efektifpedia/
display_url: https://chipper26.github.io/efektifpedia/

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }