backend:
  name: github
  repo: chipper26/efektifpedia
  branch: main # Diperbarui dari master ke main sesuai repo GitHub kamu
  proxy_url: https://api.netlify.com/auth # Penting jika kamu pakai bantuan Netlify Auth

site_url: https://chipper26.github.io/efektifpedia/
display_url: https://chipper26.github.io/efektifpedia/

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog" # Sveltia akan otomatis buat folder 'blog' di root saat artikel pertama dipublish
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }