backend:
  name: github
  repo: chipper26/efektifpedia
  branch: main
  base_url: https://api.sveltia.org
  auth_endpoint: /auth

# Mengaktifkan alur kerja editorial untuk memisahkan Draft dan Publish
publish_mode: editorial_workflow

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Artikel Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # Menambahkan ringkasan tampilan agar daftar artikel lebih informatif
    summary: "{{title}} | {{author}} | {{status}}" 
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - label: "Metadata"
        name: "meta"
        widget: "object"
        fields:
          - { label: "Thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Penulis", name: "author", widget: "select", options: ["TRI IRAWAN", "Budi Darmawan"], default: "TRI IRAWAN" }
          - { label: "Kategori", name: "category", widget: "select", options: ["Edukasi", "Tips", "Berita"], default: "Edukasi" }
          - { label: "Tanggal", name: "date", widget: "datetime" }