name: Efektifpedia AI Writer Bot

on:
  schedule:
    # Berjalan 3 kali sehari (Format UTC):
    # 00:10 UTC = 07:10 WIB (Berita Pagi)
    # 06:10 UTC = 13:10 WIB (Berita Siang)
    # 12:10 UTC = 19:10 WIB (Berita Malam)
    # Digeser ke menit 10 agar lebih lancar dari antrean server GitHub.
    - cron: '10 0,6,12 * * *'
  workflow_dispatch: 

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Generate Content
        env:
          # Menghapus spasi ekstra agar pembacaan secret lebih stabil
          OPENROUTER_API_KEY: ${{secrets.OPENROUTER_API_KEY}}
          PEXELS_API_KEY: ${{secrets.PEXELS_API_KEY}}
        run: python ai_writer.py

      - name: Commit and Push
        run: |
          git config --local user.email "bot@efektifpedia.com"
          git config --local user.name "Efektifpedia Bot"
          git add .
          # Menambahkan timestamp pada commit agar riwayat lebih informatif
          git commit -m "AI: Update Content - $(date)" || exit 0
          git push