name: Efektifpedia AI Auto Bot

on:
  schedule:
    # 06:10 UTC = 13:10 WIB (Berita Siang)
    # 12:10 UTC = 19:10 WIB (Berita Malam)
    # 00:10 UTC = 07:10 WIB (Berita Pagi)
    - cron: '10 0,6,12 * * *'
  workflow_dispatch: 

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Utama
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate Content
        env:
          OPENROUTER_API_KEY: ${{secrets.OPENROUTER_API_KEY}}
          PEXELS_API_KEY: ${{secrets.PEXELS_API_KEY}}
        # Script Python ini akan menghasilkan file .md di folder blog/
        run: python ai_writer.py

      - name: Push to Storage Repo (Keyy26-git)
        env:
          # Token dari akun Keyy26-git yang disimpan di Secrets chipper26
          REMOTE_TOKEN: ${{ secrets.EXTERNAL_TOKEN }}
        run: |
          # 1. Konfigurasi Identitas Bot
          git config --local user.email "bot@efektifpedia.com"
          git config --local user.name "Efektifpedia AI Bot"
          
          # 2. Tambahkan file .md hasil generate tadi
          git add blog/
          git commit -m "AI News: Auto Update Content - $(date)" || exit 0
          
          # 3. Kirim ke Repo Gudang (External)
          # Menggunakan URL dengan Token agar lolos izin akses (403 Forbidden)
          git push https://x-access-token:${REMOTE_TOKEN}@github.com/Keyy26-git/efektifpedia-content.git main --force