name: Efektifpedia AI Writer Bot

on:
  schedule:
    # Berjalan 3 kali sehari (Format UTC):
    # 00:00 UTC = 07:00 WIB (Berita Pagi)
    # 06:00 UTC = 13:00 WIB (Berita Siang)
    # 12:00 UTC = 19:00 WIB (Berita Malam)
    - cron: '0 0,6,12 * * *'
  workflow_dispatch: 

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Generate Content
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }} # WAJIB ADA agar gambar muncul
        run: python ai_writer.py

      - name: Commit and Push
        run: |
          git config --local user.email "bot@efektifpedia.com"
          git config --local user.name "Efektifpedia Bot"
          git add .
          git commit -m "AI: Update Content - $(date)" || exit 0
          git push